# Generated by Django 5.2.17 on 2026-08-29 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0002_assessmentquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentquestion',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10),
        ),
    ]
