# Generated by Django 5.2.17 on 2026-09-16 02:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_careerskill'),
        ('assessment', '0004_assessmentresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentquestion',
            name='career_paths',
            field=models.ManyToManyField(blank=True, related_name='assessment_questions', to='accounts.careerpath'),
        ),
        migrations.AddField(
            model_name='assessmentquestion',
            name='skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessment_questions', to='accounts.skill'),
        ),
    ]
