# Generated by Django 5.2.17 on 2026-09-17 00:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_careerskill'),
        ('assessment', '0005_assessmentquestion_career_paths_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillassessment',
            name='career_path',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_assessments', to='accounts.careerpath'),
        ),
    ]
