# Generated by Django 5.2.17 on 2026-08-14 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_careerpath'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningRoadmap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('duration', models.CharField(blank=True, max_length=100)),
                ('difficulty', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='Beginner', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('career_path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roadmaps', to='accounts.careerpath')),
            ],
        ),
    ]
